version: "3"

services:
    mysql:
      image: $MYSQL_VERSION
      container_name: "mydatastack-mysql"
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: local
        MYSQL_PASSWORD: local_password
      ports:
        - "3306:3306"
      volumes:
        - './data/mysql:/var/lib/mysql'
    mongodb:
      image: $MONGO_VERSION
      container_name: "mydatastack-mongodb"
      restart: always
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/mongodb:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
      container_name: elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata1:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - esnet
    elasticsearch2:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
      container_name: elasticsearch2
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elasticsearch"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata2:/usr/share/elasticsearch/data
      networks:
        - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
